# Generated by Django 5.1.5 on 2025-01-20 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=10)),
                ('description', models.TextField(max_length=5000)),
                ('catalogue', models.CharField(choices=[('t-shirt', 'T-SHIRT'), ('watch', 'WATCH'), ('electric', 'ELECTRIC'), ('automobile', 'AUTOMOBILE')], max_length=30)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product_catalog.seller')),
            ],
        ),
    ]
