# Generated by Django 5.1.5 on 2025-01-23 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0003_alter_seller_options_alter_seller_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={},
        ),
        migrations.AlterModelManagers(
            name='seller',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='seller',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='email',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='user_permissions',
        ),
    ]
