# Generated by Django 5.1.5 on 2025-01-25 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0004_alter_seller_options_alter_seller_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='username',
        ),
    ]
