# Generated by Django 5.1.5 on 2025-09-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalog', '0006_alter_product_seller_delete_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='product',
            name='catalogue',
            field=models.CharField(max_length=30),
        ),
    ]
